/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDrawerHeaderSection: typeof import('./src/@core/components/AppDrawerHeaderSection.vue')['default']
    AppLoadingIndicator: typeof import('./src/components/AppLoadingIndicator.vue')['default']
    ApprovalStatusBadge: typeof import('./src/modules/Finance/components/ApprovalStatusBadge.vue')['default']
    AppStepper: typeof import('./src/@core/components/AppStepper.vue')['default']
    BarangForm: typeof import('./src/modules/Master/components/BarangForm.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseModal: typeof import('./src/components/base/BaseModal.vue')['default']
    BaseSelect: typeof import('./src/components/base/BaseSelect.vue')['default']
    BaseTable: typeof import('./src/components/base/BaseTable.vue')['default']
    BrandForm: typeof import('./src/modules/Master/components/BrandForm.vue')['default']
    DeferredApexChart: typeof import('./src/components/shared/DeferredApexChart.vue')['default']
    DetailRow: typeof import('./src/components/shared/DetailRow.vue')['default']
    DialogCloseBtn: typeof import('./src/@core/components/DialogCloseBtn.vue')['default']
    DropZone: typeof import('./src/@core/components/DropZone.vue')['default']
    I18n: typeof import('./src/@core/components/I18n.vue')['default']
    InvestorForm: typeof import('./src/modules/Master/components/InvestorForm.vue')['default']
    InvoiceItemRow: typeof import('./src/modules/Finance/components/InvoiceItemRow.vue')['default']
    InvoiceStatusBadge: typeof import('./src/modules/Finance/components/InvoiceStatusBadge.vue')['default']
    KaryawanForm: typeof import('./src/modules/Master/components/KaryawanForm.vue')['default']
    KlienArForm: typeof import('./src/modules/Finance/components/KlienArForm.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    PageHeader: typeof import('./src/components/shared/PageHeader.vue')['default']
    PembayaranForm: typeof import('./src/modules/Finance/components/PembayaranForm.vue')['default']
    PerusahaanForm: typeof import('./src/modules/Master/components/PerusahaanForm.vue')['default']
    PicArDashboardSection: typeof import('./src/modules/Finance/components/PicArDashboardSection.vue')['default']
    RestoForm: typeof import('./src/modules/Master/components/RestoForm.vue')['default']
    RoleForm: typeof import('./src/modules/IAM/components/RoleForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./src/@core/components/ScrollToTop.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UserForm: typeof import('./src/modules/IAM/components/UserForm.vue')['default']
  }
}
