/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgingReportSection: typeof import('./src/modules/Finance/components/laporan-sections/AgingReportSection.vue')['default']
    AppDrawerHeaderSection: typeof import('./src/@core/components/AppDrawerHeaderSection.vue')['default']
    AppLoadingIndicator: typeof import('./src/components/AppLoadingIndicator.vue')['default']
    ApprovalStatusBadge: typeof import('./src/modules/Finance/components/ApprovalStatusBadge.vue')['default']
    AppStepper: typeof import('./src/@core/components/AppStepper.vue')['default']
    BarangForm: typeof import('./src/modules/Master/components/BarangForm.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseModal: typeof import('./src/components/base/BaseModal.vue')['default']
    BaseSelect: typeof import('./src/components/base/BaseSelect.vue')['default']
    BaseTable: typeof import('./src/components/base/BaseTable.vue')['default']
    BrandForm: typeof import('./src/modules/Master/components/BrandForm.vue')['default']
    DeferredApexChart: typeof import('./src/components/shared/DeferredApexChart.vue')['default']
    DetailRow: typeof import('./src/components/shared/DetailRow.vue')['default']
    DialogCloseBtn: typeof import('./src/@core/components/DialogCloseBtn.vue')['default']
    DirectorDashboardSection: typeof import('./src/modules/Finance/components/DirectorDashboardSection.vue')['default']
    DropZone: typeof import('./src/@core/components/DropZone.vue')['default']
    EntitasForm: typeof import('./src/modules/Master/components/EntitasForm.vue')['default']
    I18n: typeof import('./src/@core/components/I18n.vue')['default']
    InvestorForm: typeof import('./src/modules/Master/components/InvestorForm.vue')['default']
    InvoiceItemRow: typeof import('./src/modules/Finance/components/InvoiceItemRow.vue')['default']
    InvoiceStatusBadge: typeof import('./src/modules/Finance/components/InvoiceStatusBadge.vue')['default']
    JatuhTempoSection: typeof import('./src/modules/Finance/components/laporan-sections/JatuhTempoSection.vue')['default']
    JurnalPicSection: typeof import('./src/modules/Finance/components/laporan-sections/JurnalPicSection.vue')['default']
    KaryawanForm: typeof import('./src/modules/Master/components/KaryawanForm.vue')['default']
    KinerjaArSection: typeof import('./src/modules/Finance/components/laporan-sections/KinerjaArSection.vue')['default']
    KlienArForm: typeof import('./src/modules/Finance/components/KlienArForm.vue')['default']
    ManagerDashboardSection: typeof import('./src/modules/Finance/components/ManagerDashboardSection.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    MutasiPiutangSection: typeof import('./src/modules/Finance/components/laporan-sections/MutasiPiutangSection.vue')['default']
    OpeningBalanceDetailItemRow: typeof import('./src/modules/Finance/components/OpeningBalanceDetailItemRow.vue')['default']
    OpeningBalanceDetailTable: typeof import('./src/modules/Finance/components/OpeningBalanceDetailTable.vue')['default']
    PageHeader: typeof import('./src/components/shared/PageHeader.vue')['default']
    PembayaranArSection: typeof import('./src/modules/Finance/components/laporan-sections/PembayaranArSection.vue')['default']
    PembayaranForm: typeof import('./src/modules/Finance/components/PembayaranForm.vue')['default']
    PicArDashboardSection: typeof import('./src/modules/Finance/components/PicArDashboardSection.vue')['default']
    RekapKlienSection: typeof import('./src/modules/Finance/components/laporan-sections/RekapKlienSection.vue')['default']
    RekapPembayaranSection: typeof import('./src/modules/Finance/components/laporan-sections/RekapPembayaranSection.vue')['default']
    RekeningKoranSection: typeof import('./src/modules/Finance/components/laporan-sections/RekeningKoranSection.vue')['default']
    RestoForm: typeof import('./src/modules/Master/components/RestoForm.vue')['default']
    RoleForm: typeof import('./src/modules/IAM/components/RoleForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./src/@core/components/ScrollToTop.vue')['default']
    SupervisorDashboardSection: typeof import('./src/modules/Finance/components/SupervisorDashboardSection.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UserForm: typeof import('./src/modules/IAM/components/UserForm.vue')['default']
  }
}
