export default [
  {
    path: '/finance/klien-ar',
    name: 'finance-klien-ar',
    component: () => import('@/modules/Finance/views/KlienArIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/klien-ar/create',
    name: 'finance-klien-ar-create',
    component: () => import('@/modules/Finance/views/KlienArFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/klien-ar/:id/edit',
    name: 'finance-klien-ar-edit',
    component: () => import('@/modules/Finance/views/KlienArFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/invoices',
    name: 'finance-invoice-index',
    component: () => import('@/modules/Finance/views/InvoiceIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/invoices/create',
    name: 'finance-invoice-create',
    component: () => import('@/modules/Finance/views/InvoiceFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/invoices/:id',
    name: 'finance-invoice-show',
    component: () => import('@/modules/Finance/views/InvoiceShow.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/invoices/:id/edit',
    name: 'finance-invoice-edit',
    component: () => import('@/modules/Finance/views/InvoiceFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/opening-balance',
    name: 'finance-opening-balance',
    component: () => import('@/modules/Finance/views/OpeningBalanceIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/opening-balance/create',
    name: 'finance-opening-balance-create',
    component: () => import('@/modules/Finance/views/OpeningBalanceFormPage.vue'),
    meta: { requiresAuth: true, roles: ['MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/opening-balance/:id/edit',
    name: 'finance-opening-balance-edit',
    component: () => import('@/modules/Finance/views/OpeningBalanceFormPage.vue'),
    meta: { requiresAuth: true, roles: ['MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/opening-balance/approval',
    name: 'finance-opening-balance-approval',
    component: () => import('@/modules/Finance/views/OpeningBalanceApprovalIndex.vue'),
    meta: { requiresAuth: true, roles: ['DIREKTUR'] },
  },
  {
    path: '/finance/aging-report',
    name: 'finance-aging-report',
    component: () => import('@/modules/Finance/views/AgingReportIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR'] },
  },
  {
    path: '/finance/rekap-klien',
    name: 'finance-rekap-klien',
    component: () => import('@/modules/Finance/views/RekapKlienIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR'] },
  },
  {
    path: '/finance/pembayaran',
    name: 'finance-pembayaran',
    component: () => import('@/modules/Finance/views/PembayaranArIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/mutasi-piutang',
    name: 'finance-mutasi-piutang',
    component: () => import('@/modules/Finance/views/MutasiPiutangIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR'] },
  },
  {
    path: '/finance/jatuh-tempo',
    name: 'finance-jatuh-tempo',
    component: () => import('@/modules/Finance/views/JatuhTempoIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/rekap-pembayaran',
    name: 'finance-rekap-pembayaran',
    component: () => import('@/modules/Finance/views/RekapPembayaranIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR'] },
  },
  {
    path: '/finance/kinerja-ar',
    name: 'finance-kinerja-ar',
    component: () => import('@/modules/Finance/views/KinerjaArIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR'] },
  },
]
