export default [
  {
    path: '/finance/klien-ar',
    name: 'finance-klien-ar',
    component: () => import('@/modules/Finance/views/KlienArIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/klien-ar/create',
    name: 'finance-klien-ar-create',
    component: () => import('@/modules/Finance/views/KlienArFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/klien-ar/:id/edit',
    name: 'finance-klien-ar-edit',
    component: () => import('@/modules/Finance/views/KlienArFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/invoices',
    name: 'finance-invoice-index',
    component: () => import('@/modules/Finance/views/InvoiceIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/invoices/create',
    name: 'finance-invoice-create',
    component: () => import('@/modules/Finance/views/InvoiceFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/invoices/:id',
    name: 'finance-invoice-show',
    component: () => import('@/modules/Finance/views/InvoiceShow.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/invoices/:id/edit',
    name: 'finance-invoice-edit',
    component: () => import('@/modules/Finance/views/InvoiceFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/opening-balance',
    name: 'finance-opening-balance',
    component: () => import('@/modules/Finance/views/OpeningBalanceIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/opening-balance/create',
    name: 'finance-opening-balance-create',
    component: () => import('@/modules/Finance/views/OpeningBalanceFormPage.vue'),
    meta: { requiresAuth: true, roles: ['MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/opening-balance/:id/edit',
    name: 'finance-opening-balance-edit',
    component: () => import('@/modules/Finance/views/OpeningBalanceFormPage.vue'),
    meta: { requiresAuth: true, roles: ['MANAGER', 'SUPERVISOR', 'AR'] },
  },
  { path: '/finance/opening-balance/approval', redirect: { name: 'finance-opening-balance' } },
  // Halaman konsolidasi laporan
  {
    path: '/finance/laporan',
    name: 'finance-laporan',
    component: () => import('@/modules/Finance/views/LaporanIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  // Redirect URL lama ke tab yang tepat di halaman laporan
  { path: '/finance/aging-report',     redirect: { name: 'finance-laporan', query: { tab: 'aging' } } },
  { path: '/finance/rekap-klien',      redirect: { name: 'finance-laporan', query: { tab: 'rekap-klien' } } },
  { path: '/finance/pembayaran',       redirect: { name: 'finance-laporan', query: { tab: 'riwayat-bayar' } } },
  { path: '/finance/mutasi-piutang',   redirect: { name: 'finance-laporan', query: { tab: 'mutasi-piutang' } } },
  { path: '/finance/rekening-koran',   redirect: { name: 'finance-laporan', query: { tab: 'rekening-koran' } } },
  { path: '/finance/jatuh-tempo',      redirect: { name: 'finance-laporan', query: { tab: 'jatuh-tempo' } } },
  { path: '/finance/rekap-pembayaran', redirect: { name: 'finance-laporan', query: { tab: 'rekap-pembayaran' } } },
  { path: '/finance/kinerja-ar',       redirect: { name: 'finance-laporan', query: { tab: 'kinerja-ar' } } },
  {
    path: '/finance/export-data',
    name: 'finance-export-data',
    component: () => import('@/modules/Finance/views/ExportDataIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR'] },
  },
  {
    path: '/finance/rekonsiliasi-bank',
    name: 'finance-rekonsiliasi-bank',
    component: () => import('@/modules/Finance/views/RekonsiliasiBankIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/rekonsiliasi-bank/:id',
    name: 'finance-rekonsiliasi-bank-show',
    component: () => import('@/modules/Finance/views/RekonsiliasiBankShow.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  { path: '/finance/jurnal-pic', redirect: { name: 'finance-laporan', query: { tab: 'jurnal-pic' } } },
]
