export default [
  {
    path: '/finance/klien-ar',
    name: 'finance-klien-ar',
    component: () => import('@/modules/Finance/views/KlienArIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/klien-ar/create',
    name: 'finance-klien-ar-create',
    component: () => import('@/modules/Finance/views/KlienArFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/klien-ar/:id/edit',
    name: 'finance-klien-ar-edit',
    component: () => import('@/modules/Finance/views/KlienArFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/invoices',
    name: 'finance-invoice-index',
    component: () => import('@/modules/Finance/views/InvoiceIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/invoices/create',
    name: 'finance-invoice-create',
    component: () => import('@/modules/Finance/views/InvoiceFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/invoices/:id',
    name: 'finance-invoice-show',
    component: () => import('@/modules/Finance/views/InvoiceShow.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/invoices/:id/edit',
    name: 'finance-invoice-edit',
    component: () => import('@/modules/Finance/views/InvoiceFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/opening-balance',
    name: 'finance-opening-balance',
    component: () => import('@/modules/Finance/views/OpeningBalanceIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/opening-balance/create',
    name: 'finance-opening-balance-create',
    component: () => import('@/modules/Finance/views/OpeningBalanceFormPage.vue'),
    meta: { requiresAuth: true, roles: ['MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/opening-balance/:id/edit',
    name: 'finance-opening-balance-edit',
    component: () => import('@/modules/Finance/views/OpeningBalanceFormPage.vue'),
    meta: { requiresAuth: true, roles: ['MANAGER', 'SUPERVISOR', 'AR'] },
  },
  { path: '/finance/opening-balance/approval', redirect: { name: 'finance-opening-balance' } },
  {
    path: '/finance/ending-balance',
    name: 'finance-ending-balance',
    component: () => import('@/modules/Finance/views/EndingBalanceIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/ending-balance/:id',
    name: 'finance-ending-balance-show',
    component: () => import('@/modules/Finance/views/EndingBalanceDetailPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/ending-balance/koreksi/approval',
    name: 'finance-ending-balance-approval',
    component: () => import('@/modules/Finance/views/EndingBalanceApprovalIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR'] },
  },
  // Halaman konsolidasi laporan
  {
    path: '/finance/laporan',
    name: 'finance-laporan',
    component: () => import('@/modules/Finance/views/LaporanIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  // Route dedicated per laporan
  {
    path: '/finance/laporan/jurnal-pic',
    name: 'finance-laporan-jurnal-pic',
    component: () => import('@/modules/Finance/views/JurnalPicIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/laporan/rekening-koran',
    name: 'finance-laporan-rekening-koran',
    component: () => import('@/modules/Finance/views/RekeningKoranIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/laporan/aging',
    name: 'finance-laporan-aging',
    component: () => import('@/modules/Finance/views/AgingReportIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/laporan/rekap-klien',
    name: 'finance-laporan-rekap-klien',
    component: () => import('@/modules/Finance/views/RekapKlienIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/laporan/riwayat-bayar',
    name: 'finance-laporan-riwayat-bayar',
    component: () => import('@/modules/Finance/views/PembayaranArIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/laporan/mutasi-piutang',
    name: 'finance-laporan-mutasi-piutang',
    component: () => import('@/modules/Finance/views/MutasiPiutangIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/laporan/rekap-pembayaran',
    name: 'finance-laporan-rekap-pembayaran',
    component: () => import('@/modules/Finance/views/RekapPembayaranIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/laporan/kinerja-ar',
    name: 'finance-laporan-kinerja-ar',
    component: () => import('@/modules/Finance/views/KinerjaArIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/laporan/pdm',
    name: 'finance-laporan-pdm',
    component: () => import('@/modules/Finance/views/PendapatanDiMukaIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  // Redirect URL lama ke route dedicated masing-masing
  { path: '/finance/aging-report',     redirect: { name: 'finance-laporan-aging' } },
  { path: '/finance/rekap-klien',      redirect: { name: 'finance-laporan-rekap-klien' } },
  { path: '/finance/pembayaran',       redirect: { name: 'finance-laporan-riwayat-bayar' } },
  { path: '/finance/mutasi-piutang',   redirect: { name: 'finance-laporan-mutasi-piutang' } },
  { path: '/finance/rekening-koran',   redirect: { name: 'finance-laporan-rekening-koran' } },
  { path: '/finance/jatuh-tempo',      redirect: { name: 'finance-laporan' } },
  { path: '/finance/rekap-pembayaran', redirect: { name: 'finance-laporan-rekap-pembayaran' } },
  { path: '/finance/kinerja-ar',       redirect: { name: 'finance-laporan-kinerja-ar' } },
  {
    path: '/finance/export-data',
    name: 'finance-export-data',
    component: () => import('@/modules/Finance/views/ExportDataIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR'] },
  },
  {
    path: '/finance/rekonsiliasi-bank',
    name: 'finance-rekonsiliasi-bank',
    component: () => import('@/modules/Finance/views/RekonsiliasiBankIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/finance/rekonsiliasi-bank/:id',
    name: 'finance-rekonsiliasi-bank-show',
    component: () => import('@/modules/Finance/views/RekonsiliasiBankShow.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  { path: '/finance/jurnal-pic', redirect: { name: 'finance-laporan-jurnal-pic' } },
]
