export default [
  {
    path: '/master/master-data',
    name: 'master-unified-import',
    component: () => import('@/modules/Master/features/MasterData/views/Index.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR'] },
  },
  {
    path: '/master/karyawan',
    name: 'master-karyawan',
    component: () => import('@/modules/Master/features/Karyawan/views/Index.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR'] },
  },
  {
    path: '/master/perusahaan',
    name: 'master-perusahaan',
    component: () => import('@/modules/Master/features/Entitas/views/Index.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR'] },
  },
  {
    path: '/master/investor',
    name: 'master-investor',
    component: () => import('@/modules/Master/features/Investor/views/Index.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/master/resto',
    name: 'master-resto',
    component: () => import('@/modules/Master/features/Resto/views/Index.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/master/brand',
    name: 'master-brand',
    component: () => import('@/modules/Master/features/Brand/views/Index.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/barang',
    name: 'master-barang',
    component: () => import('@/modules/Master/features/Barang/views/Index.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/master/karyawan/create',
    name: 'master-karyawan-create',
    component: () => import('@/modules/Master/features/Karyawan/views/Form.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR'] },
  },
  {
    path: '/master/karyawan/:id/edit',
    name: 'master-karyawan-edit',
    component: () => import('@/modules/Master/features/Karyawan/views/Form.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR'] },
  },
  {
    path: '/master/perusahaan/create',
    name: 'master-perusahaan-create',
    component: () => import('@/modules/Master/features/Entitas/views/Form.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR'] },
  },
  {
    path: '/master/perusahaan/:id/edit',
    name: 'master-perusahaan-edit',
    component: () => import('@/modules/Master/features/Entitas/views/Form.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'MANAGER', 'SUPERVISOR'] },
  },
  {
    path: '/master/investor/create',
    name: 'master-investor-create',
    component: () => import('@/modules/Master/features/Investor/views/Form.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/investor/:id/edit',
    name: 'master-investor-edit',
    component: () => import('@/modules/Master/features/Investor/views/Form.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/resto/create',
    name: 'master-resto-create',
    component: () => import('@/modules/Master/features/Resto/views/Form.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/resto/:id/edit',
    name: 'master-resto-edit',
    component: () => import('@/modules/Master/features/Resto/views/Form.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/brand/create',
    name: 'master-brand-create',
    component: () => import('@/modules/Master/features/Brand/views/Form.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/brand/:id/edit',
    name: 'master-brand-edit',
    component: () => import('@/modules/Master/features/Brand/views/Form.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/barang/create',
    name: 'master-barang-create',
    component: () => import('@/modules/Master/features/Barang/views/Form.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/barang/:id/edit',
    name: 'master-barang-edit',
    component: () => import('@/modules/Master/features/Barang/views/Form.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
]
