export default [
  {
    path: '/master/karyawan',
    name: 'master-karyawan',
    component: () => import('@/modules/Master/views/KaryawanIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/perusahaan',
    name: 'master-perusahaan',
    component: () => import('@/modules/Master/views/PerusahaanIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/investor',
    name: 'master-investor',
    component: () => import('@/modules/Master/views/InvestorIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/master/resto',
    name: 'master-resto',
    component: () => import('@/modules/Master/views/RestoIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/master/brand',
    name: 'master-brand',
    component: () => import('@/modules/Master/views/BrandIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/barang',
    name: 'master-barang',
    component: () => import('@/modules/Master/views/BarangIndex.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN', 'DIREKTUR', 'MANAGER', 'SUPERVISOR', 'AR'] },
  },
  {
    path: '/master/karyawan/create',
    name: 'master-karyawan-create',
    component: () => import('@/modules/Master/views/KaryawanFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/karyawan/:id/edit',
    name: 'master-karyawan-edit',
    component: () => import('@/modules/Master/views/KaryawanFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/perusahaan/create',
    name: 'master-perusahaan-create',
    component: () => import('@/modules/Master/views/PerusahaanFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/perusahaan/:id/edit',
    name: 'master-perusahaan-edit',
    component: () => import('@/modules/Master/views/PerusahaanFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/investor/create',
    name: 'master-investor-create',
    component: () => import('@/modules/Master/views/InvestorFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/investor/:id/edit',
    name: 'master-investor-edit',
    component: () => import('@/modules/Master/views/InvestorFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/resto/create',
    name: 'master-resto-create',
    component: () => import('@/modules/Master/views/RestoFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/resto/:id/edit',
    name: 'master-resto-edit',
    component: () => import('@/modules/Master/views/RestoFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/brand/create',
    name: 'master-brand-create',
    component: () => import('@/modules/Master/views/BrandForm.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/brand/:id/edit',
    name: 'master-brand-edit',
    component: () => import('@/modules/Master/views/BrandForm.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/barang/create',
    name: 'master-barang-create',
    component: () => import('@/modules/Master/views/BarangFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
  {
    path: '/master/barang/:id/edit',
    name: 'master-barang-edit',
    component: () => import('@/modules/Master/views/BarangFormPage.vue'),
    meta: { requiresAuth: true, roles: ['ADMIN'] },
  },
]
