export default [
  {
    title: 'Dashboard',
    to: { name: 'dashboard' },
    icon: { icon: 'ri-home-smile-2-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'],
  },
  {
    title: 'Export Data',
    to: { name: 'finance-export-data' },
    icon: { icon: 'ri-download-2-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR'],
  },
  { heading: 'USER MANAGEMENT' },
  {
    title: 'Data User',
    to: { name: 'iam-users' },
    icon: { icon: 'ri-user-3-line' },
    roles: ['ADMIN'],
  },
  {
    title: 'Data Karyawan',
    to: { name: 'master-karyawan' },
    icon: { icon: 'ri-contacts-line' },
    roles: ['ADMIN'],
  },
  {
    title: 'Data Role',
    to: { name: 'iam-roles' },
    icon: { icon: 'ri-shield-user-line' },
    roles: ['ADMIN'],
  },
  {
    title: 'Data Entitas',
    to: { name: 'master-perusahaan' },
    icon: { icon: 'ri-building-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR'],
  },
  { heading: 'MASTER DATA' },
  {
    title: 'Import Master Data',
    to: { name: 'master-unified-import' },
    icon: { icon: 'ri-file-upload-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR'],
  },
  {
    title: 'Data Investor',
    to: { name: 'master-investor' },
    icon: { icon: 'ri-money-dollar-circle-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'],
  },
  {
    title: 'Data Resto',
    to: { name: 'master-resto' },
    icon: { icon: 'ri-store-2-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'],
  },
  {
    title: 'Data Brand',
    to: { name: 'master-brand' },
    icon: { icon: 'ri-price-tag-3-line' },
    roles: ['ADMIN'],
  },
  {
    title: 'Data Barang',
    to: { name: 'master-barang' },
    icon: { icon: 'ri-box-3-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'],
  },
  { heading: 'ACCOUNT RECEIVABLE' },
  {
    title: 'Client',
    to: { name: 'finance-klien-ar' },
    icon: { icon: 'ri-building-4-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'],
  },
  {
    title: 'Invoice',
    to: { name: 'finance-invoice-index' },
    icon: { icon: 'ri-file-list-3-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'],
  },
  {
    title: 'Opening Balance',
    to: { name: 'finance-opening-balance' },
    icon: { icon: 'ri-history-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'],
  },
  {
    title: 'Ending Balance',
    to: { name: 'finance-ending-balance' },
    icon: { icon: 'ri-scales-2-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'],
  },
  { heading: 'ACCOUNT PAYABLE' },
  {
    title: 'Dashboard AP',
    to: { name: 'ap-dashboard' },
    icon: { icon: 'ri-dashboard-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AP'],
  },
  {
    title: 'Import SHZ360',
    to: { name: 'ap-shz360-import-index' },
    icon: { icon: 'ri-refresh-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AP'],
  },
  {
    title: 'Vendor',
    to: { name: 'ap-vendor-index' },
    icon: { icon: 'ri-store-2-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AP'],
  },
  {
    title: 'Tagihan',
    to: { name: 'ap-tagihan-index' },
    icon: { icon: 'ri-bill-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AP'],
  },
  {
    title: 'Opening Balance',
    to: { name: 'ap-opening-balance-index' },
    icon: { icon: 'ri-history-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AP'],
  },
  {
    title: 'Payment Voucher',
    to: { name: 'ap-pembayaran-index' },
    icon: { icon: 'ri-bank-card-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AP'],
  },
  {
    title: 'Ending Balance',
    to: { name: 'ap-ending-balance-index' },
    icon: { icon: 'ri-scales-2-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AP'],
  },
  { heading: 'REKONSILIASI' },
  {
    title: 'Rekonsiliasi Bank',
    to: { name: 'finance-rekonsiliasi-bank' },
    icon: { icon: 'ri-bank-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'],
  },
  { heading: 'LAPORAN' },
  {
    title: 'Laporan',
    to: { name: 'finance-laporan' },
    icon: { icon: 'ri-file-chart-line' },
    roles: ['ADMIN', 'MANAGER', 'SUPERVISOR', 'AR'],
  },
]
